// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetAllNotes() {
  return window['go']['main']['App']['GetAllNotes']();
}

export function GetNoteByDate(arg1) {
  return window['go']['main']['App']['GetNoteByDate'](arg1);
}

export function GetNotesByMonth(arg1) {
  return window['go']['main']['App']['GetNotesByMonth'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2);
}

export function SaveOrUpdateNoteByDate(arg1, arg2) {
  return window['go']['main']['App']['SaveOrUpdateNoteByDate'](arg1, arg2);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}
